chsize: 1000
worker: 0

input:
  - type: redis
    host: 127.0.0.1:6379
    key:  filebeat-nginx
    connections: 1

output:
  - type: elastic
    url:
      - "http://127.0.0.1:9200"
    index: "log-nginx-%{+@2006-01-02}"
    document_type: "%{type}"
